#!/usr/bin/env python

from conway.gol import gol

def main(args):
    game = gol(args)
    while game.state == 'initial':
        key = game.win.getch()
        if key in [ord('s'),ord('r')]:
            game.state = 'run'
        if key == ord('q'):
            return
    game.Start()
    return

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("-f", "--fullscreen", action="store_true",
                        default=False, help="display fullscreen grid")
    parser.add_argument("-x", "--no_hud", action="store_true",
                        default=False, help="don't display HUD")
    parser.add_argument("-t", "--traditional", action="store_true",
                        default=False, help="traditional mode")
    parser.add_argument("-r", default=0.02, type=float, metavar="refresh_rate",
                        help="set the refresh rate")
    parser.add_argument("-n", type=int, metavar="initial_points",
                        help="set the number of initial points")
    main(parser.parse_args())
